# Generated by Django 5.2.7 on 2025-10-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7c6b_idx',
            old_name='notifications_user_is_read_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_ea918f_idx',
            old_name='notifications_type_idx',
        ),
    ]
