# Generated by Django 5.2.7 on 2025-10-11 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('loan', 'Loan'), ('reservation', 'Reservation')], default='loan', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('loaned_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('renew_count', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'type'], name='loans_loan_status_bea0d5_idx'), models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'), models.Index(fields=['book', 'status'], name='loans_loan_book_id_f87641_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'pending']), ('type', 'loan')), fields=('user', 'book'), name='uniq_user_book_active_pending_loan'), models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('type', 'reservation')), fields=('user', 'book'), name='uniq_user_book_pending_reservation')],
            },
        ),
    ]
