# Generated by Django 5.2.7 on 2025-10-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_created_at_book_updated_at_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='books_available_lte_total',
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__gte', 0)), name='books_available_lte_total'),
        ),
    ]
